### ISSUE TITLE
User Story: User-friendly website

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#1]
As a **public user**, I **want a user-friendly interactive website** so that **bookings are easy to make**

## Acceptance Criteria:
- Booking details are visible on home page
- Responsive in mobile and desktop browsers
- Feedback on user actions are given
- User finds links to navigate to other functions easy
- Font is legible 
- Color contrast is effective

## Tasks
  - [x] Chose a color scheme for the website
  - [x] Chose the fonts to use
  - [x] Create the logo
  - [x] Create the HTML and CSS for the drop-down menus on home page
  - [x] Create the model and views for the booking on home page
  - [x] Deploy to Heroku
  - [x] Create feedback to user actions
  - [x] Test the completed home page.
