### ISSUE TITLE
User Story: Receive email confirmation

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#10]
In order to **know of successful booking/cancellation** as **a public user**, I can **receive email notifications**
## Acceptance Criteria:
  - Email is received upon confirmation/cancellation of booking
## Tasks
  - [x] Create the email template
  - [x] Add email send details to settings.py and env.py
  - [x] Send email after confirmation of booking
  - [x] Send email after  cancellation of a booking
  - [x] Test functionality

**Comment by Polyanyanwu** [comment]
Completed and tested
