### ISSUE TITLE
User Story: Operator cancel booking

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#11]
As **an operator**, I can **cancel bookings where guest fail to turn up after a given time has elapsed** so that **the seats could become available to use**

## Acceptance Criteria:
  - Menu option for cancel booking available
  - Ability to select all active bookings
  - Button to pick and cancel a booking
  - Confirmation to proceed with the cancellation
  - Feedback message on successful cancellation
  - Updated list of active bookings

## Tasks
  - [x] Add cancel booking to Operator menu
  - [x] Create a cancel booking template and view with list of active bookings and button to cancel an item
  - [x] Create a confirmation modal form and request confirmation of cancellation
  - [x] Create a feedback for the cancellation outcome
  - [x] Display updated list of active bookings
  - [x] Test functionality
