### ISSUE TITLE
User Story: Operator update booking status

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#12]
As **an operator**, I can **update booking status** so that **seats could become available after service has been delivered**
## Acceptance Criteria:
  - Menu option for update booking is available
  - A page is provided where active bookings are displayed
  - Buttons are provided to click and select to update status
  - Status of booking changes after confirmation of status change

## Tasks
  - [x] Add update booking to operator menu
  - [x] Create update booking template and view
  - [x] Create a confirmation modal form and request confirmation of status change
  - [x] Create a feedback for the status change outcome
  - [x] Test the functionality

**Comment by Polyanyanwu** [comment]
Completed and tested okay
