### ISSUE TITLE
User Story: Book on behalf of customer

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#13]
As **an operator**, I can **make booking on behalf of a customer** so that **customers that call in on phone could receive service**.

## Acceptance Criteria:
  - Make booking option is available for operator
  - Operator can find the customer using phone or email address
  - Successful booking visible on booking history enquiry 

## Tasks
  - [x] Add make booking to operator menu
  - [x] Create form for booking for customer
  - [x] When saved send email to customer and update booking table
  - [x] Test the functionality

**Comment by Polyanyanwu** [comment]
Done, reused the booking by customer by supplying the user to book for to the view and template
