### ISSUE TITLE
Project initiation

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#17]
Project initiation tasks
## Tasks
- [x] Create User Stories on Github
- [x] Design Wireframes 
- [x] Design Model Schema
- [x] Decide on fonts, color scheme and other content
- [x] Setup application requirements on Gitpod

**Comment by Polyanyanwu** [comment]
Finished wireframe design

**Comment by Polyanyanwu** [comment]
Project successfully deployed to Heroku with required libraries
