### ISSUE TITLE
User Story:  Create Account

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#18]
As a **prospective user**, I can to **create an account** so that I can **complete bookings in the application**.
## Acceptance Criteria:
  - Signup option is available to user on the home page and when trying to complete a booking
  - Successful signup will enable user login with the created email and password

## Tasks
  - [x] Create signup page
  - [x] Create the profile page
  - [x] Test the functionality
