### ISSUE TITLE
User Story: Sign in

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#19]
As **registered user**, I can **have an effective interface** so that **I will sign-in and sign-out easily**

## Acceptance Criteria:
  - Sign-in link available on home page 
  - Sign-in page opens when link is clicked
  - Sign-out link available after sign-in
  - Full user menu is available when successfully signed in

## Tasks
  - [x] Add sign-in link to home page
  - [x] Create sign-in page
  - [x] Create sign-out page
  - [x] Enable full user menu to signed in user

**Comment by Polyanyanwu** [comment]
Sign in and Sign out completed and tested
