### ISSUE TITLE
User Story: Access on different devices

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#2]
As a **public user**, I can **access the website using different devices** so that **I will have same friendly experience**.
## Acceptance Criteria:
  - Website is accessible on different sized devices
  - Information is easy to find both on small and large screens 
## Tasks
  - [x] Use Bootstrap responsive design on all pages
  - [x] Ensure logo, title and menus appear on all pages consistently
  - [x] Test the functionality
