### ISSUE TITLE
User Story: Reset password

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#20]
As **registered user**, I can **change my password** so that **it is safe at all times.**
## Acceptance Criteria:
  - Reset password link available at sign-in page
  - Reset password page opens and enables user successfully reset password

## Tasks
  - [x] Add Reset link to sign-in page
  - [x] Copy and modify Django allauth files for reset password
  - [x] Adjust any needed settings and url
  - [x] Test the full flow of password reset
