### ISSUE TITLE
User Story:  Update Profile

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#21]
As **signed-in user**, I can **update information to my profile** so that **I have effective interaction with the application**.
## Acceptance Criteria:
  - Profile option available to signed in user
  - Profile page opens and enables user to change names/phone or email as needed 

## Tasks
  - [x] Add the profile template from Django allauth 
  - [x] Modify the template to suite custom fields
  - [x] Adjust any needed settings and url
  - [x] Test the full flow of profile change
