### ISSUE TITLE
User Story: Assign user roles

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#22]
In order to **manage access to the site** as **Admin**, I can **assign user role to registered users**
## Acceptance Criteria:
  - Options for user role is available on the user profile
  - Setting the user role restricts the user to the assigned role 

## Tasks
  - [x] Modify the profile template to add user role
  - [x] Ensure model has user role
  - [x] Model the role descriptions

**Comment by Polyanyanwu** [comment]
Allauth came with the feature
