### ISSUE TITLE
User Story: System preferences

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#23]
In order to **make the application flexible** as **Admin**, I can **set system preferences**
## Acceptance Criteria:
  - System preferences available in the Admin panel
  - Changes made affect the working of the application

## Tasks
  - [x] Model system preferences
  - [x] Make the model available to Admin
  - [x] Create any necessary models
