### ISSUE TITLE
User Story: Buffet types

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#26]
In order to **render updated services to the public** as **Admin**, I can **maintain buffet categories (meal menu) including description, price and image of the buffet**
## Acceptance Criteria:
  - Buffet types table available for maintenance in Admin panel
  - Changes made at the Admin panel reflects on the main site

## Tasks
  - [x] Create model for the buffet types
  - [x] Update the settings and URLs to add to Admin panel
  - [x] Test the functionality

**Comment by Polyanyanwu** [comment]
It was necessary to create the table before the home page could be fully constructed
