### ISSUE TITLE
User Story:  Maintain table/seats

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#27]
In order to **increase/decrease the seat facilities** as **Admin**, I can **maintain table/seat types and quantities available**
## Acceptance Criteria:
  - Table/Seats available to update on the Admin panel
  - Changes made at the Admin panel reflects on the main site

## Tasks
  - [x] Create model for the table/seats
  - [x] Update the settings and URLs to add to Admin panel
  - [x] Test the functionality

**Comment by Polyanyanwu** [comment]
The tables became necessary to create as the home page depends on them
