### ISSUE TITLE
User Story: Select number of people on booking form

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#3]
As a **public user**, I can **have option to select number of people for the dinner** so that **the availability will be confirmed immediately**

## Acceptance Criteria:
  - On the booking form a selection box is available with options for number of people
## Tasks
  - [x] Create the model for table and seats
  - [x] On the model for booking, create select option
  - [x] Test the functionality

**Comment by Polyanyanwu** [comment]
Done
