### ISSUE TITLE
User Story: Delete fulfilled Bookings

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#34]
As an **administrator** I can **delete fulfilled bookings**,  so that **the application will keep being responsive**

## Acceptance Criteria:
  - Booking deleted successfully and not appearing on the booking list
 
## Tasks
  - [x] Create a template for displaying the booking list
  - [x] Create a view and add search capability to display only fulfilled bookings
  - [x] Add the url to access the functionality
  - [x] Add the functionality to the Administrator menu
  - [x] Test the functionality

**Comment by Polyanyanwu** [comment]
Functionality tested okay
