### ISSUE TITLE
User Story: Edit booking by Customer

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#35]
As a <**Customer**> I can <**edit my booking when reviewing the list of bookings**>,  so that <**its more intuitive instead of cancel booking first and then book new one**>

## Acceptance Criteria:
  - Booking details changed as per edited dates/persons/time
  -  Edited booking available on list of upcoming bookings
## Tasks
  - [x] Create a template for the editing of booking 
  - [x] Create a view for processing the edit actions
  - [x] Create the urls
  - [x] Test the editing function

**Comment by Polyanyanwu** [comment]
Completed and tested
