### ISSUE TITLE
User Story: Time options available on booking form

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#5]
In order to **book a specific time** as a **public user**, I can **have time options to select from on a chosen date**.
## Acceptance Criteria:
  - On the booking form a selection box is available with options for available time slots

## Tasks
  - [x] Create model for time slots
  - [x] Connect the available time slots to the booking form
  - [x] Display only available time slots
  - [x] Test the functionality

**Comment by Polyanyanwu** [comment]
User sees all time slots and check is carried out when user clicks to submit
