### ISSUE TITLE
User Story: Make booking

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#6]
As a **public user**, I can **make booking** so that **the dinner time is confirmed**.
## Acceptance Criteria:
  - Booking form is available to user
  - Signup form is available to user
  - A signed-in user can save a booking and receive immediate confirmation plus an email
## Tasks
  - [x] Add email confirmation to booking
  - [x] Check that user is signed-in to save booking or redirect to signup page if not signed-in
  - [x] Verify from the model that seats are available for selected time and date and give feedback
  - [x] Test the functionality

**Comment by Polyanyanwu** [comment]
Done
