### ISSUE TITLE
User Story: Display details of buffet types

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#7]
In order to <**receive-benefit**>  as a <**role**>, I can <*goal-desire**>
In order to **know the type of meals available** as a **public user**, I can **see images and descriptions of buffet types**.
## Acceptance Criteria:
  - Images and description of buffet types available on the booking page

## Tasks
  - [x] Create model and view for maintain buffet types
  - [x] Display buffet type on booking page
  - [x] Test the functionality

**Comment by Polyanyanwu** [comment]
Done
