### ISSUE TITLE
User Story: Public cancel booking

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#8]
In order to **inform the restaurant of my unavailability** as **a public user**, I can **cancel a booking**.

## Acceptance Criteria:
  - Menu has option for cancel booking
  - Cancel booking page has details of all active bookings
  - A button is available to click and cancel desired booking
  - Feedback is given and list of bookings updated immediately

## Tasks
  - [x] Add cancel booking as user menu option
  - [x] Create list of all active bookings on the cancel booking page
  - [x] Give immediate feedback if successfully cancelled
  - [x] Refresh the page display to show the booking has been cancelled
  - [x] Add the cancelled booking to the Notifications page
  - [x] Test the functionality

**Comment by Polyanyanwu** [comment]
Completed and tested
