### ISSUE TITLE
User Story: Public view booking history

### ISSUE THREAD

**Issue by Polyanyanwu** [Polyanyanwu/graces-buffet-pp4#9]
In order to **know the times I was at the restaurant** as **a public user**, I can **view booking history**
## Acceptance Criteria:
  - Option for booking history available on the menu
  - Booking history page contains details of all previous bookings

## Tasks
  - [x] Add booking history to user menu option
  - [x] Create booking history template and view
  - [x] Test the functionality

**Comment by Polyanyanwu** [comment]
Done
